services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blacktigerq8
      POSTGRES_PASSWORD: Aa66850080!
      POSTGRES_DB: school
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: school_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://blacktigerq8:Aa66850080!@postgres:5432/school
      - NEXTAUTH_SECRET=x/HLUkgbdC+r4p9mR6ycSs3OcSOOXE081Jg3+y24PCQ=
      - NEXTAUTH_URL=http://5.182.18.226:3000
      - NODE_ENV=production

volumes:
  postgres_data:
